version: '3.8'

services:
  api:
    build: .
    deploy:
      replicas: 4
    environment:
      - PING_LISTEN_PORT=3000

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"

